export const itemsPath = '/images/items/'
export const appearancePath = '/images/appearance/'
export const usersPath = '/images/avatars/'
export const missionsPath = '/images/missions/'
export const ralliesPath = '/images/rallies/'
export const productsPath = '/images/products/'